# fly.toml app configuration file
app = "my-fastapi-app"   # <-- change this to your app name from `fly launch`
primary_region = "gru"   # choose a region close to you (e.g. gru = São Paulo, mia = Miami, cdg = Paris)

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true   # scales down to zero when idle
  auto_start_machines = true  # wakes on request
  min_machines_running = 0
  max_machines_running = 3
  processes = ["app"]